### ISSUE TITLE
asyncWrapper should set center value on map load

### ISSUE THREAD

**Issue by markv** [terence55/react-baidu-maps#1]
@terence55 
In the example [here](https://github.com/terence55/react-baidu-maps/blob/master/samples/src/components/AsyncDemo.js) we have to use `componentDidMount` to set the pan value after a timeout.

I think this should be moved into the `asyncWrapper` so I can do:
```<AsyncMap center={lat: lat, lon: lon}/>```
and have the map automatically centered when the component mounts.

If I use ```<AsyncMap zoom={zoom}/>``` it works when the component mounts so center should work as well

**Comment by terence55** [comment]
@markv 
Thanks for your suggestion.
There may be something wrong in the function `setCenter` of BaiduMaps. It does not work even I try to use it like this:

```
var map = new BMap.Map("allmap");
map.setCenter(new BMap.Point(118.127294, 24.438853));
```

Now the implementation of center modification has been changed to `centerAndZoom`. 2 new props have been added(defaultCenter & defaultZoom). They could be used to set the initial values. The original props(center & zoom) should be used as controlled props in React, and the samples have already been updated.
