### ISSUE TITLE
React Baidu maps Issue with react 16.7.0

### ISSUE THREAD

**Issue by gayatrijagtap** [terence55/react-baidu-maps#10]
When using react-baidu-maps with React 16.7 version, we are getting below error:

**Element ref was specified as a string (%s) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information**

However, it works fine with React 15 version.

**Comment by terence55** [comment]
I run the sample project with react 16.7.0, but I can not reproduce it.
Please provide a reproducible demo in codesandbox or codepen if you need more help.
