### ISSUE TITLE
how can I popup infowindow onMouseOver

### ISSUE THREAD

**Issue by shakeelkoper** [terence55/react-baidu-maps#11]
function hoverHandle(}) {
    console.log('~~~~~hoverHandle~~~~~');
  }

onMouseOver={hoverHandle}

As I was not able to find the example as wel

**Comment by darshanapatil** [comment]
I agree I also need onMouseOver Event.

**Comment by checkomkar** [comment]
Please add mouseOver event which can display tooltip or other operations

**Comment by anaskhan23** [comment]
Please add mouseover on InfoWindow.
Infowindow.js > Line 167
this.props[_constants.MARKER].addEventListener('mouseover', this.openWindow);

**Comment by terence55** [comment]
Sorry for replying late, actually the function that pop-up after clicking is just for ease of use, you can control the display and hiding of InfoWindow through common React modes(such as State). But for convenience, I will make InfoWindow support 2 trigger modes(hover and click).
