### ISSUE TITLE
Can you please add MouseOver Event for InfoWindow

### ISSUE THREAD

**Issue by darshanapatil** [terence55/react-baidu-maps#12]
I have gone through the library you have added only Click event for InfoWindow.
Can you any solution to use any other events.

**Comment by anaskhan23** [comment]
Please add mouseover on InfoWindow.
Infowindow.js > Line 167
this.props[_constants.MARKER].addEventListener('mouseover', this.openWindow);

**Comment by darshanapatil** [comment]
> Please add mouseover on InfoWindow.
> Infowindow.js > Line 167
> this.props[_constants.MARKER].addEventListener('mouseover', this.openWindow);

Hey Buddy! Thank for identifying the exact code. It will help the owner to make the changes quickly.
@terence55 FYI please check it once .

**Comment by terence55** [comment]
Sorry for replying late, here is the same issue and solution.
https://github.com/terence55/react-baidu-maps/issues/11
