### ISSUE TITLE
Please add onMouseOver event so that we can display tooltip

### ISSUE THREAD

**Issue by checkomkar** [terence55/react-baidu-maps#13]

**Comment by anaskhan23** [comment]
Please add mouseover on InfoWindow.
Infowindow.js > Line 167
` this.props[_constants.MARKER].addEventListener('mouseover', this.openWindow);`

**Comment by terence55** [comment]
Sorry for replying late, here is the same issue and solution.
https://github.com/terence55/react-baidu-maps/issues/11
