### ISSUE TITLE
Customizing Marker Cluster Icon

### ISSUE THREAD

**Issue by anaskhan23** [terence55/react-baidu-maps#14]
@terence55 I would like to customise marker cluster icon, I am not able to overriding the image path. It is taking default icons only on the basis of no. Of markers.

**Comment by dipeshsak** [comment]
> @terence55 I would like to customise marker cluster icon, I am not able to overriding the image path. It is taking default icons only on the basis of no. Of markers.

Hey Thanks @anaskhan23 for raising.
@terence55 i am facing kind off same issue.

**Comment by terence55** [comment]
Actually MarkerClusterer is a third-party library for Baidu Map, and i just integrated it into this project as a component. For more detailed information, you can view the author's documentation and examples here.
http://api.map.baidu.com/library/MarkerClusterer/1.2/docs/symbols/BMapLib.MarkerClusterer.html
http://api.map.baidu.com/library/MarkerClusterer/1.2/examples/simple.htm

For icon customization, you need to define the MarkerCluster style in a certain format.
Also add a sample for that.
https://github.com/terence55/react-baidu-maps/blob/master/samples/src/components/MarkerClustererDemo.js
