### ISSUE TITLE
如何添加工具条

### ISSUE THREAD

**Issue by jacktang** [terence55/react-baidu-maps#15]
<img width="554" alt="截屏2020-07-12 下午10 03 46" src="https://user-images.githubusercontent.com/44341/87248395-dc13ba00-c48b-11ea-8239-f5c3445452a5.png">

如何添加类似上述页面右上的工具条呢？多谢！

**Comment by terence55** [comment]
Baidu地图SDK本身不支持这个工具条，建议按照实际需求自己开发，叠加到地图上即可。测距可以通过类似在地图上增加Polyline，标记可以通过在地图上增加Marker来实现。分享需要按照实际需求具体开发，取决于你的产品要分享到哪些平台。
