### ISSUE TITLE
Add InfoWindow component for Marker

### ISSUE THREAD

**Issue by markv** [terence55/react-baidu-maps#3]
@terence55 I'm trying to place a marker with some information on the map but there does not seem to be any component that implements InfoWindow:

http://developer.baidu.com/map/reference/index.php?title=Class:%E8%A6%86%E7%9B%96%E7%89%A9%E7%B1%BB/InfoWindow

http://lbsyun.baidu.com/index.php?title=jspopular/guide/infowindow

This would be a very useful component to have and would be a great addition to this library.

**Comment by terence55** [comment]
@markv
Thanks for your suggestion.
InfoWindow has been added, and the samples have already been updated.
