### ISSUE TITLE
BMap Uncaught SyntaxError: Unexpected

### ISSUE THREAD

**Issue by qiuziz** [terence55/react-baidu-maps#4]
![image](https://user-images.githubusercontent.com/13669987/40759620-7660d940-64c5-11e8-80ab-50cb390701b4.png)
Error in device mode，but no error in web mode.

![image](https://user-images.githubusercontent.com/13669987/40759719-e2d88f32-64c5-11e8-9298-b4b30d9bd61d.png)

Do you know why?

**Comment by terence55** [comment]
There is no the same problem in the sample project, it seems that there are some errors in you request url `http://api.map.baidu.com/getscript...`. If you need further help, please provide a reproducible demo in codesandbox or codepen.

**Comment by qiuziz** [comment]
I found the problem，caused by a plugin.

![image](https://user-images.githubusercontent.com/13669987/40769061-96d73f9c-64e9-11e8-949d-d2232c01fea9.png)

no error when I disable it.

thx
