### ISSUE TITLE
如何根据search内容添加覆盖物？

### ISSUE THREAD

**Issue by danranshizhi** [terence55/react-baidu-maps#5]
根据搜索关键词，添加覆盖物，
this.refs.map1.search("搜索关键词")这种写法是不对的，请问这个要怎么样写？

**Comment by terence55** [comment]
这个组件提供的是百度地图的React方式渲染，如果是使用百度地图本身的功能，可以直接调用其接口。这里通过refs拿到的是BaiduMap这个React组件，是没有search方法的，如果要search，请使用BMap.LocalSearch。另外，通过组件的getBMap方法可以拿到当前的BMap实例。
http://lbsyun.baidu.com/index.php?title=jspopular/guide/search

```js
<BaiduMap
  ...
  ref={instance => (this.map = instance)} />

<button onClick={() => {
  const mapInstance = this.map.getBMap();
  // 如果使用的是异步方式加载，这里写作 const mapInstance = this.map.getWrappedInstance().getBMap();
  const local = new BMap.LocalSearch(mapInstance, {
    renderOptions: { map: mapInstance }
  });
  local.search('搜索关键词');
  }}>Search</button>
```
