### ISSUE TITLE
InfoWindow使用报错

### ISSUE THREAD

**Issue by danranshizhi** [terence55/react-baidu-maps#7]
import { BaiduMap , Marker , MarkerClusterer , Polyline , InfoWindow  } from 'react-baidu-maps';
<Marker position={{ lng: datas.lon, lat: datas.lat }} key={count++}>
        <InfoWindow content="<div style='color: red;'>I am red</div>" offset={{ width: 0, height: -20 }} />
</Marker>
已经import,使用时还是报错Cannot read property 'propTypes' of undefined

**Comment by terence55** [comment]
谢谢反馈，是有点问题，InfoWindow是后面应要求新加的组件，没有从index中导出。已经发布了新版，npm更新下即可
