### ISSUE TITLE
怎么设置地图的主题色

### ISSUE THREAD

**Issue by danranshizhi** [terence55/react-baidu-maps#8]
<BaiduMap
            enableScrollWheelZoom
            enableDragging={this.state.enableDragging}
            defaultZoom={this.state.zoom}
            id="location"
            mapContainer={<div style={{ height: document.body.clientHeight-62-40 }} />}
            ref={instance => (this.map = instance)}
            setMapStyle = {() => (
              "styleJson":[
                {
          		   "featureType": "all",
          		   "elementType": "geometry",
          		   "stylers": {
          					 "hue": "#007fff",
          					 "saturation": 89
          		   }
          	}
            ]
          )}>
这样设置是没有效果的，请问要如何设置

**Comment by terence55** [comment]
BaiduMap有mapStyle属性，直接设置即可，所有已经对接到百度地图的属性都能在BaiduMap的controlledPropTypes里看到
